version: '3.3'
services:
  db:
    image: mysql:8.0.23
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
    security_opt:
      - seccomp:unconfined
    env_file:
      - .env
    ports:
      - $DB_PORT:$DB_PORT
    expose:
      - '$DB_PORT'
    volumes:
      - ./sql:/sql
      - my-db:/var/lib/mysql

  mongodb:
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  my-db:
  mongodb: